### ISSUE TITLE
editing ?

### ISSUE THREAD

**Issue by gedw99** [steverusso/mdedit#16]
Wonderful and fast editor !!! Is a joy to use...

Does this supporting editing a markdown file ?

The buffer golang file seems to indicate that there is some lower level functionality for this, but maybe its not exposed to the Text Editor ?

**Comment by steverusso** [comment]
> Wonderful and fast editor !!! Is a joy to use...

Thank you, although it is still very much a work-in-progress haha.

> Does this supporting editing a markdown file ?

Sorry, I don't understand the question. If you provide a file path to the program (for example `mdedit file.md`), you should be able to edit the markdown content of `file.md`, correct?

**Comment by gedw99** [comment]
Yes i know its very alpha / beta, etc :) I am just playing around with the it as its such a nice example of what gioui can do.

Yes parsing a file as an argument works fine.

But I  can not edit the markdown. The same is true for all files i open with it. There is no caret. Its completely read only.

I am in mac btw. Maybe your on windows or linux and are not aware that editing does not work ?

**Comment by steverusso** [comment]
Yikes... no I didn't know that, I'm only using linux. Just to be clear, you're saying when you open a file, for example by running `mdedit file.md`, there is no white rectangle in the top left corner of the file content, such as the below screenshot?

![image](https://user-images.githubusercontent.com/6127189/172000101-e89cc525-0a2c-4bd4-8463-f3b72f81272c.png)

**Comment by gedw99** [comment]
I also have the white rectangle. However, i cant edit because no mouse or keyboard events work to allow editing the file. The panel is totally dead.
The preview panel ( on the right) works great. Scrolls etc.

**Comment by steverusso** [comment]
Ah, ok: the editor is meant to be similar to vim. I say ["vi-like" in the readme](https://github.com/steverusso/mdedit#mdedit). So that rectangle is the caret.

Vim (stands for Vi-IMproved) is a text editor with different "modes." Two of the most often used modes are Normal mode and Insert mode.

By default, `mdedit` starts in Normal mode which is useful for navigating around the text. Check out [this Vim cheatsheet](https://vim.rtorr.com/), specifically the "Cursor movement" section for how to use Normal mode.

To start editing check out the next section titled "Insert mode - inserting/appending text." (A common way is by just typing `i` if you wanted to quickly try it without reading the cheatsheet).

**Comment by gedw99** [comment]
Ah . all makes sense now.

I can confirm that inserts work on mac. SO no bug - just user training :)

**Comment by steverusso** [comment]
Haha yes, and I can probably be clearer about this in the readme, so thank you for the issue! :sunglasses:

**Comment by gedw99** [comment]
ah its cool - thats code - never ever finished... 

I did find your code for checking the key binding events. It is so nicely done.

I started to make a markdown file to document all the currently implemented key bindings, but could not because i do not understand how to use VIM and so cant document the same in mdedit. Not enough  semantic understanding on my side..

If you happen to get time to add these to the README with some sort of explanation it would be really cool.   I really want to use this as my IDE , and yes i know its beta beta...  Please let me know if you do make the markdown doc, otherwise i will try again later when i have more time.
